version: "3"
services:
  app:
    container_name: tiff-labelwriter
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_ENV=development
      - FLASK_APP=app.py